# Generated by Django 5.1.5 on 2025-02-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SsqOtherPredict',
            fields=[
                ('issueNumber', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('result', models.TextField()),
            ],
        ),
    ]
